
import React, { createContext, useContext, useState, useEffect } from 'react';

interface AppContextType {
  language: 'es' | 'en' | 'pt' | 'ru';
  setLanguage: (lang: 'es' | 'en' | 'pt' | 'ru') => void;
  darkMode: boolean;
  setDarkMode: (dark: boolean) => void;
  notifications: Notification[];
  addNotification: (notification: Omit<Notification, 'id' | 'timestamp' | 'read'>) => void;
  markNotificationAsRead: (id: string) => void;
  markAllNotificationsAsRead: () => void;
}

interface Notification {
  id: string;
  title: string;
  message: string;
  read: boolean;
  timestamp: Date;
  type: 'success' | 'info' | 'warning' | 'error';
}

const AppContext = createContext<AppContextType | undefined>(undefined);

export const translations = {
  es: {
    dashboard: 'Terapia Bilateral',
    reports: 'Reportes',
    history: 'Historial',
    configuration: 'Configuración',
    trainingMode: 'Entrenamiento',
    therapyMode: 'Terapia',
    systemTitle: 'Terapia Robótica Bilateral',
    monitoringSystem: 'Sistema de Terapias',
    rehabilitation: 'Rehabilitación Robótica Bilateral Post-ACV',
    realTimeMonitoring: 'Monitoreo en Tiempo Real',
    nonPareticHand: 'Mano No Parética',
    pareticHand: 'Mano Parética',
    withSensors: 'Con Sensores',
    withExoskeleton: 'Con Exoesqueleto',
    inactive: 'Inactivo',
    active: 'Activo',
    therapyTimer: 'Temporizador de Terapia',
    duration: 'Duración (minutos)',
    start: 'Iniciar',
    pause: 'Pausar',
    restart: 'Reiniciar',
    ready: 'Listo',
    achievements: 'Logros de',
    weeklyProgress: 'Progreso semanal',
    monthlyProgress: 'Progreso mensual',
    completed: 'completado esta semana',
    effortAnalysis: 'Análisis de Esfuerzo del Paciente',
    patientAnalysis: 'Análisis del Paciente',
    averageWeeklyTime: 'Tiempo promedio semanal',
    minutes: 'min',
    week: 'semana',
    currentWeek: 'Semana actual',
    previousWeek: 'Semana anterior',
    notifications: 'Notificaciones',
    markAsRead: 'Marcar como leída',
    markAllAsRead: 'Marcar todas como leídas',
    noNotifications: 'No hay notificaciones',
    congratulationsTraining: 'Felicidades por completar el entrenamiento diario',
    sessionCompleted: 'Sesión de terapia completada exitosamente',
    locale: 'es-ES',
    // Rankings
    position: 'Pos.',
    date: 'Fecha',
    glasses: 'Vasos',
    oranges: 'Naranjas',
    timePerGlass: 'Tiempo/Vaso',
    timePerOrange: 'Tiempo/Naranja',
    score: 'Puntaje',
    pointsPerSecond: 'Pts/Seg',
    pointsPerMinute: 'Pts/Min',
    noRecords: 'No hay registros aún',
    loginToViewRankings: 'Inicia sesión para ver rankings',
    rankingOrangeSqueeze: 'Ranking - Exprimiendo Naranjas',
    rankingNeuroLink: 'Ranking - NeuroDefense',
    rankingFlappyBird: 'Ranking - RehabBird',
    // Hand Monitoring
    articulationAngles: 'Ángulos de Articulación',
    thumb: 'Pulgar',
    fingers: 'Dedos',
    // Simulator
    dataSimulator: 'Simulador de Datos',
    mqttConnected: 'MQTT Conectado',
    mqttDisconnected: 'MQTT Desconectado',
    receivingRealData: 'Recibiendo datos reales - Simulador deshabilitado',
    connectedNoData: 'Conectado pero sin datos - Habilite el simulador',
    enableSimulator: 'Habilitar Simulador',
    useSimulatedData: 'Usar datos simulados',
    automaticMode: 'Modo Automático',
    randomDataEvery30s: 'Datos aleatorios cada 30s',
    leftHandActive: 'Mano Izq. Activa',
    rightHandActive: 'Mano Der. Activa',
    leftHandNonParetic: 'Mano Izquierda (No Parética)',
    rightHandParetic: 'Mano Derecha (Parética)',
    // History Page
    historyDescription: 'Historial cronológico de tus sesiones de rehabilitación',
    loadingHistory: 'Cargando historial...',
    noSessionsRecorded: 'No hay sesiones registradas',
    completeFirstSession: 'Completa tu primera sesión de terapia o entrenamiento para ver tu historial aquí.',
    orangeGameTitle: 'Juego de Naranjas',
    neuroLinkTitle: 'NeuroDefense',
    guidedTherapyTitle: 'Terapia Guiada',
    therapySession: 'Sesión de Terapia',
    completedStatus: 'Completada',
    cancelled: 'Cancelada',
    activeSession: 'Activa',
    unknown: 'Desconocido',
    guidedTherapySummary: 'Resumen de Terapia Guiada',
    averageOpening: 'Promedio Apertura',
    averageClosing: 'Promedio Cierre',
    movements: 'Movimientos',
    opening: 'Apertura',
    closing: 'Cierre',
    total: 'Total',
    viewLess: 'Ver menos',
    viewMore: 'Ver más',
    orangeGameSummary: 'Resumen del Juego de Naranjas',
    squeezedOranges: 'Naranjas exprimidas',
    completedGlasses: 'Vasos completados',
    finalScore: 'Puntuación',
    neuroLinkSummary: 'Resumen de NeuroDefense',
    levelReached: 'Nivel alcanzado',
    accuracy: 'Precisión',
    loadMore: 'Cargar más sesiones',
    muscularEffort: 'Esfuerzo Muscular',
    leftHand: 'Mano Izquierda',
    rightHand: 'Mano Derecha',
    sendSimulatedData: 'Enviar Datos Simulados',
    usingRealData: 'Usando Datos Reales',
    automaticModeActive: 'Modo Automático Activo',
    simulatorDisabled: 'Simulador Deshabilitado',
    logout: 'Cerrar sesión',
    days: 'días',
    completedThisWeek: 'completado esta semana',
    completedThisMonth: 'completado este mes',
    // Filters
    filters: 'Filtros',
    hideFilters: 'Ocultar',
    showFilters: 'Mostrar',
    therapyType: 'Tipo de terapia',
    selectType: 'Seleccionar tipo',
    allTypes: 'Todos',
    dateFrom: 'Desde',
    dateTo: 'Hasta',
    selectDate: 'Seleccionar fecha',
    applyFilters: 'Aplicar filtros',
    clearFilters: 'Limpiar filtros',
    // Main page
    greeting: '¡Hola,',
    greetingJoy: 'Qué alegría verte hoy.',
    dailyGoalText: 'Tu meta de hoy:',
    minutesToKeepProgress: 'minutos para mantener tu progreso.',
    therapyHub: 'Centro de Terapia',
    therapyHubHint: 'Coloca el guante y el exoesqueleto antes de empezar.',
    startSessionBtn: 'COMENZAR SESIÓN',
    suggestedDuration: 'Duración sugerida',
    paused: 'Pausado',
    yourAchievements: 'Tus Avances y Logros',
    realTimeVisualization: 'Visualización en Tiempo Real del Sistema',
    recommended: '(recomendado)'
  },
  en: {
    dashboard: 'Bilateral Therapy',
    reports: 'Reports',
    history: 'History',
    configuration: 'Configuration',
    trainingMode: 'Training',
    therapyMode: 'Therapy',
    systemTitle: 'Bilateral Robotic Therapy',
    monitoringSystem: 'Therapy System',
    rehabilitation: 'Post-Stroke Bilateral Robotic Rehabilitation',
    realTimeMonitoring: 'Real-Time Monitoring',
    nonPareticHand: 'Non-Paretic Hand',
    pareticHand: 'Paretic Hand',
    withSensors: 'With Sensors',
    withExoskeleton: 'With Exoskeleton',
    inactive: 'Inactive',
    active: 'Active',
    therapyTimer: 'Therapy Timer',
    duration: 'Duration (minutes)',
    start: 'Start',
    pause: 'Pause',
    restart: 'Restart',
    ready: 'Ready',
    achievements: 'Achievements of',
    weeklyProgress: 'Weekly progress',
    monthlyProgress: 'Monthly progress',
    completed: 'completed this week',
    effortAnalysis: 'Patient Effort Analysis',
    patientAnalysis: 'Patient Analysis',
    averageWeeklyTime: 'Weekly average time',
    minutes: 'min',
    week: 'week',
    currentWeek: 'Current week',
    previousWeek: 'Previous week',
    notifications: 'Notifications',
    markAsRead: 'Mark as read',
    markAllAsRead: 'Mark all as read',
    noNotifications: 'No notifications',
    congratulationsTraining: 'Congratulations on completing daily training',
    sessionCompleted: 'Therapy session completed successfully',
    locale: 'en-US',
    // Rankings
    position: 'Pos.',
    date: 'Date',
    glasses: 'Glasses',
    oranges: 'Oranges',
    timePerGlass: 'Time/Glass',
    timePerOrange: 'Time/Orange',
    score: 'Score',
    pointsPerSecond: 'Pts/Sec',
    pointsPerMinute: 'Pts/Min',
    noRecords: 'No records yet',
    loginToViewRankings: 'Login to view rankings',
    rankingOrangeSqueeze: 'Ranking - Orange Squeeze',
    rankingNeuroLink: 'Ranking - NeuroDefense',
    rankingFlappyBird: 'Ranking - RehabBird',
    // Hand Monitoring
    articulationAngles: 'Joint Angles',
    thumb: 'Thumb',
    fingers: 'Fingers',
    // Simulator
    dataSimulator: 'Data Simulator',
    mqttConnected: 'MQTT Connected',
    mqttDisconnected: 'MQTT Disconnected',
    receivingRealData: 'Receiving real data - Simulator disabled',
    connectedNoData: 'Connected but no data - Enable simulator',
    enableSimulator: 'Enable Simulator',
    useSimulatedData: 'Use simulated data',
    automaticMode: 'Automatic Mode',
    randomDataEvery30s: 'Random data every 30s',
    leftHandActive: 'Left Hand Active',
    rightHandActive: 'Right Hand Active',
    leftHandNonParetic: 'Left Hand (Non-Paretic)',
    rightHandParetic: 'Right Hand (Paretic)',
    // History Page
    historyDescription: 'Chronological history of your rehabilitation sessions',
    loadingHistory: 'Loading history...',
    noSessionsRecorded: 'No sessions recorded',
    completeFirstSession: 'Complete your first therapy or training session to see your history here.',
    orangeGameTitle: 'Orange Squeeze Game',
    neuroLinkTitle: 'NeuroDefense',
    guidedTherapyTitle: 'Guided Therapy',
    therapySession: 'Therapy Session',
    completedStatus: 'Completed',
    cancelled: 'Cancelled',
    activeSession: 'Active',
    unknown: 'Unknown',
    guidedTherapySummary: 'Guided Therapy Summary',
    averageOpening: 'Average Opening',
    averageClosing: 'Average Closing',
    movements: 'Movements',
    opening: 'Opening',
    closing: 'Closing',
    total: 'Total',
    viewLess: 'View less',
    viewMore: 'View more',
    orangeGameSummary: 'Orange Game Summary',
    squeezedOranges: 'Squeezed Oranges',
    completedGlasses: 'Completed Glasses',
    finalScore: 'Score',
    neuroLinkSummary: 'NeuroDefense Summary',
    levelReached: 'Level Reached',
    accuracy: 'Accuracy',
    loadMore: 'Load more sessions',
    muscularEffort: 'Muscular Effort',
    leftHand: 'Left Hand',
    rightHand: 'Right Hand',
    sendSimulatedData: 'Send Simulated Data',
    usingRealData: 'Using Real Data',
    automaticModeActive: 'Automatic Mode Active',
    simulatorDisabled: 'Simulator Disabled',
    logout: 'Logout',
    days: 'days',
    completedThisWeek: 'completed this week',
    completedThisMonth: 'completed this month',
    // Filters
    filters: 'Filters',
    hideFilters: 'Hide',
    showFilters: 'Show',
    therapyType: 'Therapy type',
    selectType: 'Select type',
    allTypes: 'All',
    dateFrom: 'From',
    dateTo: 'To',
    selectDate: 'Select date',
    applyFilters: 'Apply filters',
    clearFilters: 'Clear filters',
    // Main page
    greeting: 'Hello,',
    greetingJoy: 'Great to see you today.',
    dailyGoalText: 'Your goal today:',
    minutesToKeepProgress: 'minutes to keep your progress.',
    therapyHub: 'Therapy Hub',
    therapyHubHint: 'Put on the glove and exoskeleton before starting.',
    startSessionBtn: 'START SESSION',
    suggestedDuration: 'Suggested duration',
    paused: 'Paused',
    yourAchievements: 'Your Achievements',
    realTimeVisualization: 'Real-Time System Visualization',
    recommended: '(recommended)'
  },
  pt: {
    dashboard: 'Terapia Bilateral',
    reports: 'Relatórios',
    history: 'Histórico',
    configuration: 'Configuração',
    trainingMode: 'Treinamento',
    therapyMode: 'Terapia',
    systemTitle: 'Terapia Robótica Bilateral',
    monitoringSystem: 'Sistema de Terapia',
    rehabilitation: 'Reabilitação Robótica Bilateral Pós-AVC',
    realTimeMonitoring: 'Monitoramento em Tempo Real',
    nonPareticHand: 'Mão Não Parética',
    pareticHand: 'Mão Parética',
    withSensors: 'Com Sensores',
    withExoskeleton: 'Com Exoesqueleto',
    inactive: 'Inativo',
    active: 'Ativo',
    therapyTimer: 'Temporizador de Terapia',
    duration: 'Duração (minutos)',
    start: 'Iniciar',
    pause: 'Pausar',
    restart: 'Reiniciar',
    ready: 'Pronto',
    achievements: 'Conquistas de',
    weeklyProgress: 'Progresso semanal',
    monthlyProgress: 'Progresso mensal',
    completed: 'completado esta semana',
    effortAnalysis: 'Análise de Esforço do Paciente',
    patientAnalysis: 'Análise do Paciente',
    averageWeeklyTime: 'Tempo médio semanal',
    minutes: 'min',
    week: 'semana',
    currentWeek: 'Semana atual',
    previousWeek: 'Semana anterior',
    notifications: 'Notificações',
    markAsRead: 'Marcar como lida',
    markAllAsRead: 'Marcar todas como lidas',
    noNotifications: 'Nenhuma notificação',
    congratulationsTraining: 'Parabéns por completar o treinamento diário',
    sessionCompleted: 'Sessão de terapia concluída com sucesso',
    locale: 'pt-BR',
    // Rankings
    position: 'Pos.',
    date: 'Data',
    glasses: 'Copos',
    oranges: 'Laranjas',
    timePerGlass: 'Tempo/Copo',
    timePerOrange: 'Tempo/Laranja',
    score: 'Pontuação',
    pointsPerSecond: 'Pts/Seg',
    pointsPerMinute: 'Pts/Min',
    noRecords: 'Ainda não há registros',
    loginToViewRankings: 'Faça login para ver os rankings',
    rankingOrangeSqueeze: 'Ranking - Espremer Laranjas',
    rankingNeuroLink: 'Ranking - NeuroDefense',
    rankingFlappyBird: 'Ranking - RehabBird',
    // Hand Monitoring
    articulationAngles: 'Ângulos de Articulação',
    thumb: 'Polegar',
    fingers: 'Dedos',
    // Simulator
    dataSimulator: 'Simulador de Dados',
    mqttConnected: 'MQTT Conectado',
    mqttDisconnected: 'MQTT Desconectado',
    receivingRealData: 'Recebendo dados reais - Simulador desabilitado',
    connectedNoData: 'Conectado mas sem dados - Habilite o simulador',
    enableSimulator: 'Habilitar Simulador',
    useSimulatedData: 'Usar dados simulados',
    automaticMode: 'Modo Automático',
    randomDataEvery30s: 'Dados aleatórios a cada 30s',
    leftHandActive: 'Mão Esq. Ativa',
    rightHandActive: 'Mão Dir. Ativa',
    leftHandNonParetic: 'Mão Esquerda (Não Parética)',
    rightHandParetic: 'Mão Direita (Parética)',
    // History Page
    historyDescription: 'Histórico cronológico das suas sessões de reabilitação',
    loadingHistory: 'Carregando histórico...',
    noSessionsRecorded: 'Nenhuma sessão registrada',
    completeFirstSession: 'Complete sua primeira sessão de terapia ou treinamento para ver seu histórico aqui.',
    orangeGameTitle: 'Jogo de Laranjas',
    neuroLinkTitle: 'NeuroDefense',
    guidedTherapyTitle: 'Terapia Guiada',
    therapySession: 'Sessão de Terapia',
    completedStatus: 'Concluída',
    cancelled: 'Cancelada',
    activeSession: 'Ativa',
    unknown: 'Desconhecido',
    guidedTherapySummary: 'Resumo da Terapia Guiada',
    averageOpening: 'Média de Abertura',
    averageClosing: 'Média de Fechamento',
    movements: 'Movimentos',
    opening: 'Abertura',
    closing: 'Fechamento',
    total: 'Total',
    viewLess: 'Ver menos',
    viewMore: 'Ver mais',
    orangeGameSummary: 'Resumo do Jogo de Laranjas',
    squeezedOranges: 'Laranjas espremidas',
    completedGlasses: 'Copos completos',
    finalScore: 'Pontuação',
    neuroLinkSummary: 'Resumo do NeuroDefense',
    levelReached: 'Nível alcançado',
    accuracy: 'Precisão',
    loadMore: 'Carregar mais sessões',
    muscularEffort: 'Esforço Muscular',
    leftHand: 'Mão Esquerda',
    rightHand: 'Mão Direita',
    sendSimulatedData: 'Enviar Dados Simulados',
    usingRealData: 'Usando Dados Reais',
    automaticModeActive: 'Modo Automático Ativo',
    simulatorDisabled: 'Simulador Desabilitado',
    logout: 'Sair',
    days: 'dias',
    completedThisWeek: 'completado esta semana',
    completedThisMonth: 'completado este mês',
    // Filters
    filters: 'Filtros',
    hideFilters: 'Ocultar',
    showFilters: 'Mostrar',
    therapyType: 'Tipo de terapia',
    selectType: 'Selecionar tipo',
    allTypes: 'Todos',
    dateFrom: 'De',
    dateTo: 'Até',
    selectDate: 'Selecionar data',
    applyFilters: 'Aplicar filtros',
    clearFilters: 'Limpar filtros',
    // Main page
    greeting: 'Olá,',
    greetingJoy: 'Que alegria ver você hoje.',
    dailyGoalText: 'Sua meta de hoje:',
    minutesToKeepProgress: 'minutos para manter seu progresso.',
    therapyHub: 'Centro de Terapia',
    therapyHubHint: 'Coloque a luva e o exoesqueleto antes de começar.',
    startSessionBtn: 'INICIAR SESSÃO',
    suggestedDuration: 'Duração sugerida',
    paused: 'Pausado',
    yourAchievements: 'Seus Avanços e Conquistas',
    realTimeVisualization: 'Visualização em Tempo Real do Sistema',
    recommended: '(recomendado)'
  },
  ru: {
    dashboard: 'Двусторонняя терапия',
    reports: 'Отчеты',
    history: 'История',
    configuration: 'Настройки',
    trainingMode: 'Тренировка',
    therapyMode: 'Терапия',
    systemTitle: 'Двусторонняя роботизированная терапия',
    monitoringSystem: 'Терапевтическая система',
    rehabilitation: 'Двусторонняя роботизированная реабилитация после инсульта',
    realTimeMonitoring: 'Мониторинг в реальном времени',
    nonPareticHand: 'Непаретичная рука',
    pareticHand: 'Паретичная рука',
    withSensors: 'С датчиками',
    withExoskeleton: 'С экзоскелетом',
    inactive: 'Неактивно',
    active: 'Активно',
    therapyTimer: 'Таймер терапии',
    duration: 'Продолжительность (минуты)',
    start: 'Начать',
    pause: 'Пауза',
    restart: 'Перезапуск',
    ready: 'Готов',
    achievements: 'Достижения',
    weeklyProgress: 'Недельный прогресс',
    monthlyProgress: 'Месячный прогресс',
    completed: 'завершено на этой неделе',
    effortAnalysis: 'Анализ усилий пациента',
    patientAnalysis: 'Анализ пациента',
    averageWeeklyTime: 'Среднее недельное время',
    minutes: 'мин',
    week: 'неделя',
    currentWeek: 'Текущая неделя',
    previousWeek: 'Предыдущая неделя',
    notifications: 'Уведомления',
    markAsRead: 'Отметить как прочитанное',
    markAllAsRead: 'Отметить все как прочитанные',
    noNotifications: 'Нет уведомлений',
    congratulationsTraining: 'Поздравляем с завершением ежедневной тренировки',
    sessionCompleted: 'Сеанс терапии успешно завершен',
    locale: 'ru-RU',
    // Rankings
    position: 'Поз.',
    date: 'Дата',
    glasses: 'Стаканы',
    oranges: 'Апельсины',
    timePerGlass: 'Время/Стакан',
    timePerOrange: 'Время/Апельсин',
    score: 'Счет',
    pointsPerSecond: 'Очк/Сек',
    pointsPerMinute: 'Очк/Мин',
    noRecords: 'Пока нет записей',
    loginToViewRankings: 'Войдите, чтобы увидеть рейтинг',
    rankingOrangeSqueeze: 'Рейтинг - Выжимание апельсинов',
    rankingNeuroLink: 'Рейтинг - NeuroDefense',
    rankingFlappyBird: 'Рейтинг - RehabBird',
    // Hand Monitoring
    articulationAngles: 'Углы суставов',
    thumb: 'Большой палец',
    fingers: 'Пальцы',
    // Simulator
    dataSimulator: 'Симулятор данных',
    mqttConnected: 'MQTT подключен',
    mqttDisconnected: 'MQTT отключен',
    receivingRealData: 'Получение реальных данных - Симулятор отключен',
    connectedNoData: 'Подключено, но нет данных - Включите симулятор',
    enableSimulator: 'Включить симулятор',
    useSimulatedData: 'Использовать симулированные данные',
    automaticMode: 'Автоматический режим',
    randomDataEvery30s: 'Случайные данные каждые 30с',
    leftHandActive: 'Левая рука активна',
    rightHandActive: 'Правая рука активна',
    leftHandNonParetic: 'Левая рука (непаретичная)',
    rightHandParetic: 'Правая рука (паретичная)',
    // History Page
    historyDescription: 'Хронологическая история ваших реабилитационных сессий',
    loadingHistory: 'Загрузка истории...',
    noSessionsRecorded: 'Нет записанных сессий',
    completeFirstSession: 'Завершите первую терапию или тренировку, чтобы увидеть историю здесь.',
    orangeGameTitle: 'Игра с Апельсинами',
    neuroLinkTitle: 'NeuroDefense',
    guidedTherapyTitle: 'Управляемая Терапия',
    therapySession: 'Сессия Терапии',
    completedStatus: 'Завершена',
    cancelled: 'Отменена',
    activeSession: 'Активна',
    unknown: 'Неизвестно',
    guidedTherapySummary: 'Сводка Управляемой Терапии',
    averageOpening: 'Среднее Открытие',
    averageClosing: 'Среднее Закрытие',
    movements: 'Движения',
    opening: 'Открытие',
    closing: 'Закрытие',
    total: 'Всего',
    viewLess: 'Показать меньше',
    viewMore: 'Показать больше',
    orangeGameSummary: 'Сводка Игры с Апельсинами',
    squeezedOranges: 'Выжатые Апельсины',
    completedGlasses: 'Завершенные Стаканы',
    finalScore: 'Счет',
    neuroLinkSummary: 'Сводка NeuroDefense',
    levelReached: 'Достигнутый Уровень',
    accuracy: 'Точность',
    loadMore: 'Загрузить еще сессии',
    muscularEffort: 'Мышечное усилие',
    leftHand: 'Левая рука',
    rightHand: 'Правая рука',
    sendSimulatedData: 'Отправить симулированные данные',
    usingRealData: 'Использование реальных данных',
    automaticModeActive: 'Автоматический режим активен',
    simulatorDisabled: 'Симулятор отключен',
    logout: 'Выйти',
    days: 'дней',
    completedThisWeek: 'завершено на этой неделе',
    completedThisMonth: 'завершено в этом месяце',
    // Filters
    filters: 'Фильтры',
    hideFilters: 'Скрыть',
    showFilters: 'Показать',
    therapyType: 'Тип терапии',
    selectType: 'Выбрать тип',
    allTypes: 'Все',
    dateFrom: 'От',
    dateTo: 'До',
    selectDate: 'Выбрать дату',
    applyFilters: 'Применить фильтры',
    clearFilters: 'Сбросить фильтры',
    // Main page
    greeting: 'Привет,',
    greetingJoy: 'Рады видеть вас сегодня.',
    dailyGoalText: 'Ваша цель на сегодня:',
    minutesToKeepProgress: 'минут для поддержания прогресса.',
    therapyHub: 'Центр Терапии',
    therapyHubHint: 'Наденьте перчатку и экзоскелет перед началом.',
    startSessionBtn: 'НАЧАТЬ СЕССИЮ',
    suggestedDuration: 'Рекомендуемая продолжительность',
    paused: 'Пауза',
    yourAchievements: 'Ваши Достижения',
    realTimeVisualization: 'Визуализация системы в реальном времени',
    recommended: '(рекомендовано)'
  }
};

export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'es' | 'en' | 'pt' | 'ru'>('es');
  const [darkMode, setDarkMode] = useState(false);
  const [notifications, setNotifications] = useState<Notification[]>([]);

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  const addNotification = (notification: Omit<Notification, 'id' | 'timestamp' | 'read'>) => {
    const newNotification: Notification = {
      ...notification,
      id: Math.random().toString(36).substr(2, 9),
      timestamp: new Date(),
      read: false
    };
    setNotifications(prev => [newNotification, ...prev]);
  };

  const markNotificationAsRead = (id: string) => {
    setNotifications(prev => 
      prev.map(notification => 
        notification.id === id ? { ...notification, read: true } : notification
      )
    );
  };

  const markAllNotificationsAsRead = () => {
    setNotifications(prev => 
      prev.map(notification => ({ ...notification, read: true }))
    );
  };

  return (
    <AppContext.Provider value={{
      language,
      setLanguage,
      darkMode,
      setDarkMode,
      notifications,
      addNotification,
      markNotificationAsRead,
      markAllNotificationsAsRead
    }}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
};

export const useTranslation = () => {
  const { language } = useApp();
  return translations[language];
};
