// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raxkyfrhigkfaimrayzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJheGt5ZnJoaWdrZmFpbXJheXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTg5MzYsImV4cCI6MjA2ODA5NDkzNn0.1ZC3jmJbRuQbTglJcaeLNXhq-0uY3LPROH6CPbXdPac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});